### ISSUE TITLE
Add option to set yes and no text

### ISSUE THREAD

**Issue by DonQuicky** [rtalbot89/flow-svg#3]
In the originial Flowchart script it is possible to change default yes-text and no-text. In your script I cannot find the option to set this to custom text.

Is it possible to set this option? If not, is it a option to get this done in a next release of your script?

**Comment by rtalbot89** [comment]
I actually thought I had included an option to do this, but it looks like I left it out. It should be reasonably quick to do, so I'll include it in the next few days


________________________________

**Comment by DonQuicky** [comment]
I will look forward to this release. Great plugin!

**Comment by rtalbot89** [comment]
Options to change yes and no text now added. A couple more associated options also added.
