### ISSUE TITLE
Cannot change yes no label

### ISSUE THREAD

**Issue by MhjnSamir** [rtalbot89/flow-svg#5]
flowSVG.config({
	w:150,
	h:60,
	labelYes: 'oo',
    labelNo: 'ooo',
});
Yes and no label is not changing. i looked at init.js but also its not working. I just dont want yes no label for my chart . Please help me if u know where i am wrong

**Comment by rtalbot89** [comment]
Firstly the README incorrectly referred to these configurations as yesLabel and noLabel. I've corrected the README. However, from your comment above it looks as if you have the correct names for the configs.

I've tried your settings above in the example in the repository and they work. I suggest that you test your configs in the example. By the way, init.js is a source file. The compiled code is in dist/.

**Comment by MhjnSamir** [comment]
Thanks its working now.. i dont know what was the error before. I just
update the flowsvg.min.js and code was same. After refreshed , its working
fine.Please can u share me the error or if its confidential its ok. Thank
you again.

**Comment by rtalbot89** [comment]
I haven't made any changes to the source code, I think it was just you refreshing that would have cleared previously cached JavaScript and SVG images. I have noticed with other projects that SVG tends to be aggressively cached in some browsers. Often I have to clear cached images and files to see changes.
